# goal
float64[9] f_ori # Direction cosines representing the task coordinate for force
float64[6] m_ori # Direction cosines representing the task coordinate for torque
geometry_msgs/Point xpd # position of end-effector w.r.t a frame attached to base
float64[] xrd # size is 3 => euler_angles(ZYX), 4 => quaternion, 9 => direction cosines
float64[3] f # force w.r.t x, y and z axis of task coordinate
float64[3] m # moment w.r.t x, y and z axis of task coordintate
float64 duration_f # duration to apply force
float64 duration_m # duration to apply moment
---
# result
geometry_msgs/Point xp
float64[] xr
float64[] q # generalized coordinates
---
# feedback
geometry_msgs/Point xp
float64[] xr
float64[3] f
float64[3] m
float64[] q
float64[] tau # generalized force